# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.documentai_v1beta3.proto import (
    document_processor_service_pb2 as google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2,
)
from google.longrunning import (
    operations_pb2 as google_dot_longrunning_dot_operations__pb2,
)


class DocumentProcessorServiceStub(object):
    """Service to call Cloud DocumentAI to process documents according to the
    processor's definition. Processors are built using state-of-the-art Google
    AI such as natural language, computer vision, and translation to extract
    structured information from unstructured or semi-structured documents.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
            "/google.cloud.documentai.v1beta3.DocumentProcessorService/ProcessDocument",
            request_serializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ProcessRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ProcessResponse.FromString,
        )
        self.BatchProcessDocuments = channel.unary_unary(
            "/google.cloud.documentai.v1beta3.DocumentProcessorService/BatchProcessDocuments",
            request_serializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.BatchProcessRequest.SerializeToString,
            response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
        )
        self.ReviewDocument = channel.unary_unary(
            "/google.cloud.documentai.v1beta3.DocumentProcessorService/ReviewDocument",
            request_serializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ReviewDocumentRequest.SerializeToString,
            response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
        )


class DocumentProcessorServiceServicer(object):
    """Service to call Cloud DocumentAI to process documents according to the
    processor's definition. Processors are built using state-of-the-art Google
    AI such as natural language, computer vision, and translation to extract
    structured information from unstructured or semi-structured documents.
    """

    def ProcessDocument(self, request, context):
        """Processes a single document.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchProcessDocuments(self, request, context):
        """LRO endpoint to batch process many documents. The output is written
        to Cloud Storage as JSON in the [Document] format.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReviewDocument(self, request, context):
        """Send a document for Human Review. The input document should be processed by
        the specified processor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DocumentProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ProcessDocument": grpc.unary_unary_rpc_method_handler(
            servicer.ProcessDocument,
            request_deserializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ProcessRequest.FromString,
            response_serializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ProcessResponse.SerializeToString,
        ),
        "BatchProcessDocuments": grpc.unary_unary_rpc_method_handler(
            servicer.BatchProcessDocuments,
            request_deserializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.BatchProcessRequest.FromString,
            response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
        ),
        "ReviewDocument": grpc.unary_unary_rpc_method_handler(
            servicer.ReviewDocument,
            request_deserializer=google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ReviewDocumentRequest.FromString,
            response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "google.cloud.documentai.v1beta3.DocumentProcessorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DocumentProcessorService(object):
    """Service to call Cloud DocumentAI to process documents according to the
    processor's definition. Processors are built using state-of-the-art Google
    AI such as natural language, computer vision, and translation to extract
    structured information from unstructured or semi-structured documents.
    """

    @staticmethod
    def ProcessDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.documentai.v1beta3.DocumentProcessorService/ProcessDocument",
            google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ProcessRequest.SerializeToString,
            google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BatchProcessDocuments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.documentai.v1beta3.DocumentProcessorService/BatchProcessDocuments",
            google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.BatchProcessRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReviewDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.documentai.v1beta3.DocumentProcessorService/ReviewDocument",
            google_dot_cloud_dot_documentai__v1beta3_dot_proto_dot_document__processor__service__pb2.ReviewDocumentRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
